The realistic values.
Smaller values are useful for observing the behavior, which is:

```
Traceback (most recent call last):
  File "/home/jean-paul/Environments/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/jean-paul/Projects/ClusterHQ/flocker/develop/flocker/acceptance/testtools.py", line 459, in _propagate_reason
    raise propagation_reason
Exception: Timed out cleaning up containers
```